name: Time Management
favicon: null
layout_spectrum: 0.89543
typography_spectrum: 0.38411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121411'
    - '#d8d4d5'
    - '#4e4b2a'
    - '#9492c4'
    - '#b59c39'
  brandStrength: 0.25
  lightness: 0.21642647311091423
  saturation: 0.12329366570338607
  rhythmicContrast: 0.5
purpose: []
